In [1]:
#Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np 
ls=[i for i in range(0,5)]
arr=np.array(ls)
print(arr)
print(arr.dtype)



[0 1 2 3 4]
int64


In [2]:
#Q2. Given a NumPy array 'arr', check if its data type is float64.
arr=np.array([1.5,2.6,3.7])
print(arr.dtype)


float64


In [3]:
#Q3.  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers. 
ls=[2+3j,4+5j,2+7j]
arr=np.array(ls)
print(arr)


[2.+3.j 4.+5.j 2.+7.j]


In [4]:
#Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.
ls=[1,4,5,6,7,8]
arr=np.array(ls)
print(arr.dtype)

arr=np.array(ls,dtype='float32')
print(arr.dtype)
print(arr)


int64
float32
[1. 4. 5. 6. 7. 8.]


In [5]:
#Q5.  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
ls=[1.2,2.3,3.4,4.5]
arr=np.array(ls)
print(arr.dtype)
print(arr)
arr=np.array(ls,dtype='float32')
print(arr.dtype)
print(arr)


float64
[1.2 2.3 3.4 4.5]
float32
[1.2 2.3 3.4 4.5]


In [6]:
#Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type. 

def func1(arr):
    return arr.shape,arr.size,arr.dtype
ls=[2,4,5,6,7,8,9]
arr=np.array(ls)
x,y,z=func1(arr)
print(x)
print(y)
print(z)    


(7,)
7
int64


In [7]:
#Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim
ls=[[2,4,6],[6,7,8],[9,3,1]]
arr=np.array(ls)
x=array_dimension(arr)
print(x)    


2


In [8]:
#Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
# size in bytes. 
def item_size_info(arr):
    if(arr.dtype=='float32'):
        x=4*arr.size
    elif(arr.dtype=='float64'):
        x=8*arr.size
    elif(arr.dtype=='int32'):
        x=4*arr.size
    elif(arr.dtype==chr):
        x= 1*arr.size
    else:
        leng=0
        for i in (arr):
            leng=leng+len(i)
        x=1*leng
    return x,arr.size
ls=["satyam","saurabh","shashank"]
arr=np.array(ls)
x,y=item_size_info(arr)  
print(x)
print(y)               


21
3


In [9]:
#Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides
ls=[1,2,3,4,5,6,7]
arr=np.array(ls)    
# print(arr)
x=array_strides(arr)
print(x)


(8,)


In [10]:
#Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
# and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
ls=[1.2,3.5,6.7,8.9]
arr=np.array(ls)
x,y=shape_stride_relationship(arr)
print(x)
print(y)    


(4,)
(8,)


In [11]:
#Q11.  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
# zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)
n=int(input("Enter your number is :"))
print(create_zeros_array(n))    


Enter your number is : 5


[0. 0. 0. 0. 0.]


In [18]:
#Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(x,y):
    arr=[]
    for i in range (0,x):
        arr1=[]
        for j in range(0,y):
            arr1.append(1)
        arr.append(arr1)
    arr2=np.array(arr)
    return arr2
x=int(input("Enter your row is :"))
y=int(input("Enter your column is :"))
print(create_ones_matrix(x,y))            


Enter your row is : 5
Enter your column is : 3


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
#Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
# `step`.
def generate_range_array(x,y,z):
    ls=list(range(x,y,z))
    arr=np.array(ls)
    return arr
x=int(input("Enter your first number is :"))
y=int(input("Enter your second no:"))
z=int(input("Enter your third number is :"))
ls1=generate_range_array(x,y,z)
print(ls1)


Enter your first number is : 1
Enter your second no: 20
Enter your third number is : 3


[ 1  4  7 10 13 16 19]


In [13]:
#Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
# (inclusive).
def generate_linear_space(x,y,z):
    return np.linspace(x,y,z)
x=int(input("Enter your first number is :"))
y=int(input("Enter your second no:"))
z=int(input("Enter your third number is :")) 
print(generate_linear_space(x,y,z))   


Enter your first number is : 1
Enter your second no: 20
Enter your third number is : 3


[ 1.  10.5 20. ]


In [14]:
#Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
# identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

n=int(input("Enter your n is :"))
arr1=create_identity_matrix(n)
print(arr1)


Enter your n is : 5


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#Q16. Write a function that takes a Python list and converts it into a NumPy array.
def converter(ls):
    return np.array(ls)
ls=[1,2,3,4,5,6,7,8,9]
arr1=converter(ls)    
print(arr1)


[1 2 3 4 5 6 7 8 9]


In [16]:
#Q17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
# same data.
ls1=[10,23,43,26,45]
arr=np.array(ls1)
arr1=arr.view()
print(arr1)
arr1[0]=1000
print(arr)
print(arr1)


[10 23 43 26 45]
[1000   23   43   26   45]
[1000   23   43   26   45]


In [17]:
#Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis
def func1(arr1,arr2):
    return np.concatenate([arr1,arr2],axis=0)
ls=[1,2,3,4]
ls1=[2,3,4,6]
arr=func1(ls,ls1)
print(arr)    


[1 2 3 4 2 3 4 6]


In [19]:
#Q19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#  concatenate`.
ls=[1,2,3,4,5]
ls1=[5,6,78,9]
arr=np.concatenate([ls1,ls])
print(arr)


[ 5  6 78  9  1  2  3  4  5]


In [20]:
#Q20. Write a function that vertically stacks multiple NumPy arrays given as a list
import numpy as np

def vertical_stack(arrays):
    return np.vstack(arrays)
arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
stacked_array = vertical_stack(arrays)
print(stacked_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
# with a given step size.
def func(x,y):
    z=int(input("step size is:"))
    arr=np.arange(x,y,z)
    return arr
x=int(input("starting index is :"))
y=int(input("ending index is :"))  
arr=func(x,y)
print(arr)


starting index is : 2
ending index is : 9
step size is: 2


[2 4 6 8]


In [22]:
#Q22.  Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
# (inclusive).
def func(spaced_gap):
    return np.linspace(0,1,spaced_gap)
n=int(input("Enter n:"))
arr=func(n)
print(arr)    


Enter n: 5


[0.   0.25 0.5  0.75 1.  ]


In [23]:
#Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
# 1000 (inclusive).
def func(spaced_gap):
    return np.logspace(1,1000,spaced_gap)
n=int(input("Enter your n :"))
arr=func(n)
print(arr)    


Enter your n : 5


[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [24]:
#Q24.  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
# are random integers between 1 and 100
arr=np.random.randint(1,100 ,(5,3))
print(arr)
import pandas as pd
df=pd.DataFrame(arr)
print(df)


[[29 13  2]
 [87 42 34]
 [25 98 42]
 [71 89 44]
 [13 96 80]]
    0   1   2
0  29  13   2
1  87  42  34
2  25  98  42
3  71  89  44
4  13  96  80


In [25]:
#Q25.  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
# with zeros. Use NumPy operations within the Pandas DataFrame.
lis=[-2,-4,20,-10,4,7,32,23,45]
arr=np.array(lis)
import pandas as pd
df=pd.DataFrame(arr)
df[0]=df[0].apply(lambda x: 0 if x<0 else x)
print(df)


    0
0   0
1   0
2  20
3   0
4   4
5   7
6  32
7  23
8  45


In [26]:
#Q26. Access the 3rd element from the given NumPy array.
arr=np.array([10,20,30,40,50])
print(arr[2])


30


In [27]:
#Q27.  Retrieve the element at index (1, 2) from the 2D NumPy array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1][2])


6


In [28]:
#Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr=np.array([3,8,2,10,5,7])
print(arr[arr>5])


[ 8 10  7]


In [29]:
#Q29.  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])


[3 4 5 6]


In [30]:
#Q30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2 ,1:])


[[2 3]
 [5 6]]


In [31]:
#Q31. .Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
# provided in another array
def func(arr,arr1):
    for i in arr1:
        print(arr[i])

ls1=[3,7,1,9,34,65,100]
index=[0,1,5,3,2,4]
arr=np.array(ls1)
print(arr)
index1=np.array(index)
print(index1)
func(arr,index1)


[  3   7   1   9  34  65 100]
[0 1 5 3 2 4]
3
7
65
9
1
34


In [32]:
#Q32.  Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
# boolean indexing.
arr=np.random.randint(1,10,10)
print(arr)
threshold=int(input("Enter your threshold:"))
result=arr[arr>threshold]
print(result)     


[5 5 5 6 3 7 4 7 8 9]


Enter your threshold: 3


[5 5 5 6 7 4 7 8 9]


In [33]:
#Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
# separate arrays for each dimension
def func(arr,arr1,arr2,arr3):
    arr4 = [arr[i] for i in range(len(arr1))]
    print(arr4)
    for i in arr1:
        for j in arr2:
            for k in arr3:
                print(arr[i][j][k])
arr=np.random.randint(1,50,(3,3,2))
# print(arr)
ls1=[0,1,2]
ls2=[0,1,2]
ls3=[0,1]
arr1=np.array(ls1)
arr2=np.array(ls2)
arr3=np.array(ls3)
func(arr,arr1,arr2,arr3)


[array([[14, 44],
       [22, 44],
       [10,  1]]), array([[16,  3],
       [10, 49],
       [47, 44]]), array([[43, 46],
       [ 8,  9],
       [47, 30]])]
14
44
22
44
10
1
16
3
10
49
47
44
43
46
8
9
47
30


In [34]:
#Q34.  Write a NumPy function that returns elements from an array where both two conditions are satisfied 
# using boolean indexing.

def condition1(i):
    if i%4==0:
        return i
def condition2(i):
    if(i%3==0):
        return i 
def function1(arr): 
    s=[]
    for i in range(len(arr)):
        for j in range(arr.size//len(arr)):
            if(condition1(arr[i][j]) and condition2(arr[i][j])):
                s.append(arr[i][j])
    return s

arr=np.random.randint(1,50,(3,4))
# print(arr)
arr1=function1(arr)
print(arr1)


[48]


In [35]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
# in separate arrays.
def func(arr,row1,col1):
    for i in range(len(row1)):
        for j in range(len(col1)):
            print(arr[i][j])
r1=int(input("Enter your row is :"))
c1=int(input("Enter your column is :"))
arr=np.random.randint(1,30,(r1,c1))
row1=[i for i in range(r1)]
col1=[i for i in range(c1)]
func(arr,row1,col1)


Enter your row is : 3
Enter your column is : 4


28
29
9
14
11
13
27
23
12
18
25
13


In [36]:
#Q36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.random.randint(1,10,(3,3))
print(arr)
arr1=[5]
print(arr+arr1)



[[2 9 4]
 [2 4 8]
 [3 4 9]]
[[ 7 14  9]
 [ 7  9 13]
 [ 8  9 14]]


In [37]:
#Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
# corresponding element in arr1 using NumPy broadcasting

arr=np.random.randint(1,5,(1,3))
arr1=np.random.randint(1,4,(3,4))
arr2=arr.reshape(3,1)
print(arr2)
print(arr1)
print(arr1*arr2)


[[4]
 [3]
 [3]]
[[3 3 3 1]
 [1 1 1 3]
 [3 3 2 1]]
[[12 12 12  4]
 [ 3  3  3  9]
 [ 9  9  6  3]]


In [39]:
#Q38.  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
# NumPy broadcasting.
arr1=np.random.randint(1,5,(1,4))
arr2=np.random.randint(1,10,(4,3))
arr2=arr2.reshape((3,4))
arr=arr2 + arr1
print(arr)


[[ 5 11  5  9]
 [ 9  6 11 10]
 [10 12  9 11]]


In [40]:
#Q39.  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
# broadcasting.
arr1=np.random.randint(1,5,(3,1))
arr2=np.random.randint(1,10,(1,3))
arr=arr2 + arr1
print(arr)


[[13  8 10]
 [10  5  7]
 [12  7  9]]


In [41]:
#Q40.  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
# broadcasting. Handle the shape incompatibility.
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,2))
# handle shape compatibility
arr3=arr2[:,1]   # slicing here
arr4=arr3.reshape((2,1)) # making the shape (2,1)
arr=arr1*arr4 
print(arr)




[[48 42 12]
 [63 27 18]]


In [42]:
#Q41.  Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
col=arr.size//len(arr)
print(col)
for i in range(col):
    print(arr[:,i].mean())


[[1 2 3]
 [4 5 6]]
3
2.5
3.5
4.5


In [43]:
#Q42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in range(len(arr)):
    print(arr[i].max())


3
6


In [44]:
#Q43. For the given array, find indices of maximum value in each column. 
arr = np.array([[1, 2, 3], [4, 5, 6]])
col=arr.size//len(arr)
for i in range(col):
    maxi=0
    r=0
    c=0
    for j in range(len(arr)):
        if(maxi<arr[j][i]):
            maxi=arr[j][i]
            r=j
            c=i
    print(f"the col indexes {i}: its maximum value {maxi} and indices is row index {r} and col index {c}\n")



the col indexes 0: its maximum value 4 and indices is row index 1 and col index 0

the col indexes 1: its maximum value 5 and indices is row index 1 and col index 1

the col indexes 2: its maximum value 6 and indices is row index 1 and col index 2



In [45]:
#Q44. For the given array, apply custom function to calculate moving sum along rows. 
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in range(len(arr)):
    print(arr[i].sum())


6
15


In [46]:
#Q45. In the given array, check if all elements in each column are even.
def Even_Col(arr):
    for i in range(len(arr)):
        if(arr[i]%2!=0):
            return False
    return True

arr = np.array([[2, 4, 6], [3, 5, 7]])
col=arr.size//len(arr)
for i in range(col):
    arr1=arr[:,i]
    print(Even_Col(arr1))
    


False
False
False


In [47]:
#Q46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
# reshaped matrix.
ori_arr= np.array([1, 2, 3, 4, 5, 6])
siz=ori_arr.size
m=int(input("Enter your m is :"))
n=int(input("Enter your n is :"))
if(m*n==siz):
    arr=ori_arr.reshape(m,n)
    print(arr)
else:
    print("Invalid input of row and column")   


Enter your m is : 3
Enter your n is : 4


Invalid input of row and column


In [48]:
#Q47. Create a function that takes a matrix as input and returns the flattened array
in_mat = np.array([[1, 2, 3], [4, 5, 6]])
arr=in_mat.flatten()
print(arr)


[1 2 3 4 5 6]


In [49]:
#Q48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate([array1,array2],axis=0)
arr1=np.concatenate([array1,array2],axis=1)
print(arr)
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [50]:
#Q49. Create a function that splits an array into multiple sub-arrays along a specified axis
ori_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr=np.hsplit(ori_arr,3)
print(arr)
arr1=np.vsplit(ori_arr,3)
print(arr1)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [51]:
#Q50. Write a function that inserts and then deletes elements from a given array at specified indices
ori_arr=np.array([1,2,3,4,5])
indice_to_insert=[2,4]
value_to_insert=[10,11]
indice_to_delete=[1,3]
def func1_insert(ori_arr,indice_to_insert,value_to_insert):
    for i in range(len(value_to_insert)):
        arr1=np.insert(ori_arr,indice_to_insert[i],value_to_insert[i])
        print(arr1)
def func1_delete(ori_arr,indice_to_delete):
    for i in range(len(indice_to_delete)):
        x=ori_arr[i]
        new_arr1=np.delete(ori_arr,indice_to_delete)
        print(new_arr1)
# print(ori_arr)        
# print(new_arr1)       
func1_insert(ori_arr,indice_to_insert,value_to_insert)
func1_delete(ori_arr,indice_to_delete)


[ 1  2 10  3  4  5]
[ 1  2  3  4 11  5]
[1 3 5]
[1 3 5]


In [52]:
#Q51.  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
# Perform element-wise addition between `arr1` and `arr2`
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
arr=arr1+arr2
print(arr1)
print(arr2)
print(arr)


[[5 3 7]
 [7 4 5]
 [7 7 4]]
[[8 3 1]
 [9 2 5]
 [6 5 5]]
[[13  6  8]
 [16  6 10]
 [13 12  9]]


In [53]:
#Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
# from 1 to 10. Subtract `arr2` from `arr1` element-wise
arr1=np.arange(1,11,1)
print(arr1)
arr=arr1.reshape(2,5)
print(arr)
arr2=np.arange(10,0,-1)
print(arr2)
arr3=arr2.reshape(2,5)
print(arr3)
final_arr=arr-arr3
print(final_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[10  9  8  7  6  5  4  3  2  1]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[-9 -7 -5 -3 -1]
 [ 1  3  5  7  9]]


In [54]:
#Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
# Perform element-wise multiplication between `arr1` and `arr2`.
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))
arr=arr1*arr2
print(arr)

[[4 8 9]
 [6 2 4]
 [2 3 8]]


In [55]:
#Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
# to 5. Perform element-wise division of `arr1` by `arr2`.
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))
arr=arr1/arr2
print(arr)

[[2.   1.5  2.  ]
 [1.   1.   1.  ]
 [0.25 0.25 0.5 ]]


In [56]:
#Q55.  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.random.randint(1,5,(3,3))
print(arr1)
arr2=arr1[::-1]
print(arr2)
arr=arr1**arr2
print(arr)


[[1 4 4]
 [4 2 3]
 [1 1 2]]
[[1 1 2]
 [4 2 3]
 [1 4 4]]
[[  1   4  16]
 [256   4  27]
 [  1   1  16]]


In [57]:
#Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_function(arr, word):
    count=0
    for i in arr:
        if word==i:
            count=count+1
    return count        


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import random 
x=random.randint(0,5)
y=count_function(arr,arr[x])
print(y)


1


In [58]:
#Q57.  Write a function that extracts uppercase characters from a NumPy array of strings.
ar1=[]
def extract_uppercase(arr):
    for i in arr:
        if i.isupper()==True:
            ar1.append(i)

            
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
extract_uppercase(arr)
print(ar1)

         

['GPT']


In [59]:
#Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def func_replace(arr,x,r_string):
    arr[x]=r_string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import random
x=random.randint(0,4)

stri=input("Enter strring is :")

func_replace(arr,x,stri)
print(arr)



Enter strring is : kela


['kela' 'banana' 'grape' 'pineapple']


In [60]:
#Q59. Write a function that concatenates strings in a NumPy array element-wise.
str3=[]
def func_concate(str1,str2):
    for i in range(len(str1)):
        s=str1[i]+str2[i]
        str3.append(s)
ls=["satyam","shash","ankur","good"]
ls1=[" saurabh","ank"," kumar"," luck"]
str1=np.array(ls)
str2=np.array(ls1)
func_concate(str1,str2)
print(str3)


['satyam saurabh', 'shashank', 'ankur kumar', 'good luck']


In [61]:
#Q60. Write a function that finds the length of the longest string in a NumPy array.
leng=0
def func_longest_string(arr,leng):
    for i in arr:
        if len(i)>leng:
            leng=len(i)
    return leng        
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
x=func_longest_string(arr,leng)
print(x)


9


In [62]:
#Q61.  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
# standard deviation of the dataset using NumPy's functions.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
arr=np.random.randint(1,1000,100)
print(arr.mean())
print(np.median(arr))
print(arr.var())
print(arr.std())


[ 16 708 551 531 223 386 174 674 544 130 314 299 614 145 309 849 924  35
  69 744 489 423 920 691 397 362 937 775  27 905 925 702 224 583 793 414
 449 905   5 296 317 178 774 123  90 508 933 555 645 746 877 707  51 212
 148 927 653 865 164 568 655 910 347 409 854 801 337 309 928 697 601 175
  86 504  68 972 407 360 749 616  16  48 836 878 941 775 922 640 420 662
 816  85  24 301 480 378 654 861 601 958]
515.83
547.5
88806.2411
298.00376021117586


In [63]:
#Q62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
# dataset.
arr=np.random.randint(1,100,50)
percentile=np.percentile(arr,[25,75])
print(" the 25th percentile is: ",percentile[0])
print(" the 75th percentile is: ",percentile[1])


 the 25th percentile is:  31.0
 the 75th percentile is:  70.75


In [64]:
#Q63.  Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
# arrays using NumPy's `corrcoef` function. 
ls1=[1,2,3,4,5]
ls2=[4,3,2,1,6]
arr1=np.array(ls1)
arr2=np.array(ls2)
coef_mat=np.corrcoef(arr1,arr2)
print(coef_mat[0,1]) # this give the correlation coefficient between arr1 and arr2.


0.1643989873053573


In [65]:
#Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(np.dot(arr1,arr2))


[[ 59  95  77]
 [ 91 133 114]
 [ 57  96  90]]


In [66]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles.
# we have function np.percentile(arr,[list of number which is numberth percentile])
arr=np.random.randint(10,1000,50)

percentile=np.percentile(arr,[10,50,90])
print(" the 10th percentiles :",percentile[0])
print(" the 50th percentiles :",percentile[1])
print(" the 90th percentiles :",percentile[2])


 the 10th percentiles : 196.0
 the 50th percentiles : 524.0
 the 90th percentiles : 851.3


In [69]:
#Q66. Create a NumPy array of integers and find the index of a specific element.
import numpy as np

def find_element_index(arr, ele):
    
    indices = np.where(arr == ele)[0]
    if indices.size > 0:
        return indices[0]
    else:
        return "Element not found."
arr = np.array([2, 3, 4, 6, 7, 8, 9, 10])
print(arr)
ele = int(input("Enter your element: "))
index = find_element_index(arr, ele)
print(f"The index is: {index}" if isinstance(index, int) else index)


[ 2  3  4  6  7  8  9 10]


Enter your element:  5


Element not found.


In [70]:
#Q67. Generate a random NumPy array and sort it in ascending order.
ls=[1,3,4,5,8,6,2]
arr=np.array(ls)
arr1=np.sort(arr)
print(arr1)


[1 2 3 4 5 6 8]


In [71]:
#Q68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])
arr1=arr[list(arr>20)]
print(arr1)


[25 42 30]


In [72]:
#Q69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])
arr1=list(filter(lambda x:x%3==0,arr))
print(arr1)


[12, 15]


In [73]:
#Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr1=list(filter(lambda x:x>=20 and x<=40,arr))
print(arr1)

[20, 30, 40]


In [74]:
#Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])
x=arr.dtype.byteorder
print(x)  # it give '='when byteorder of array is 'little' and '|' when byteorder of array is 'big'


=


In [75]:
#Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr=np.array([2,3,4,5,6,78,9])
arr1=arr.byteswap()
print(arr1)



[ 144115188075855872  216172782113783808  288230376151711744
  360287970189639680  432345564227567616 5620492334958379008
  648518346341351424]


In [76]:
#Q73. For the given NumPy array, swap its byte order without modifying the original array using 
# `newbyteorder()`
arr=np.array([1,2,3,4,5,67,8,90])
arr1=arr.newbyteorder()   # byteorder is not callable but newbyteorder is callable.
print(arr1)


[  72057594037927936  144115188075855872  216172782113783808
  288230376151711744  360287970189639680 4827858800541171712
  576460752303423488 6485183463413514240]


In [77]:
#Q74.  For the given NumPy array and swap its byte order conditionally based on system endianness using 
# `newbyteorder()`.
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
arr=arr.newbyteorder('big' if sys.byteorder=='little' else 'little') 
# from this function newbyteorder -> we convert one byteorder to another
print(arr)



[16777216 33554432 50331648]


In [78]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
# attribute `byteorder`.
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
byte_swap_needed =  (sys.byteorder=='int32')
if byte_swap_needed:
    print("it is needed")
else:
    print("not needed")    



not needed


In [79]:
#Q76.  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
ls=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(ls)
# print(arr)
arr1=arr.copy()
print(arr1)
arr1[4]=100
print(arr)
print(arr1)
# don't effect 'arr1'


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4 100   6   7   8   9  10]


In [80]:
#Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr=np.random.randint(1,10,(3,3))
arr1=arr[1:,1:]
arr1[0][1]=10
arr1[1][1]=1000
print(arr1)
print(arr)


[[   8   10]
 [   2 1000]]
[[   9    6    7]
 [   1    8   10]
 [   2    2 1000]]


In [82]:
#Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
ls=[i for i in range(1,13)]
arr=np.array(ls)
arr1=arr.reshape((4,3))
arr2=arr1[1]
print(arr2+5)
print(arr1)
# not effected


[ 9 10 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [84]:
#Q79.  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
# reflects changes in the original `orig_array`.
ls=[i for i in range(1,9)]
arr=np.array(ls)
arr1=arr.reshape((2,4))
arr2=arr1.reshape((4,2))
print(arr2)
arr2[3][1]=100
arr2[2][1]=20
print(arr2)
print(arr1)
# affected arr1


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[  1   2]
 [  3   4]
 [  5  20]
 [  7 100]]
[[  1   2   3   4]
 [  5  20   7 100]]


In [85]:
#Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
arr=np.random.randint(1,20,(3,4))
print(arr)
arr1=arr[arr>5]
print(arr1)
arr1[5]=21
arr1[4]=26
print(arr1)
print(arr)
# not effected


[[19  2 12  6]
 [11 16 15 11]
 [10 17 18 15]]
[19 12  6 11 16 15 11 10 17 18 15]
[19 12  6 11 26 21 11 10 17 18 15]
[[19  2 12  6]
 [11 16 15 11]
 [10 17 18 15]]


In [86]:
#81.  Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
# operations between them.
import numpy.matlib as nm 
arr1=nm.random.randint(1,10,(3,3))
arr2=nm.random.randint(1,10,(3,3))
print(arr1+arr2)
print(arr1-arr2)

[[11 13  5]
 [13  7 12]
 [ 5 15 16]]
[[-1  5  3]
 [ 5  3  2]
 [-1  3 -2]]


In [87]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication
arr1=nm.random.randint(1,10,(3,2))
arr2=nm.random.randint(1,10,(2,4))
print(nm.dot(arr1,arr2))


[[ 77  68 117  27]
 [ 81  82 117  23]
 [ 54  65  72  10]]


In [88]:
#Q83. Create a matrix `E` and find its transpose
arr1=nm.random.randint(1,10,(3,3))
print(arr1)
print(arr1.T)

[[1 5 8]
 [8 9 6]
 [5 3 9]]
[[1 8 5]
 [5 9 3]
 [8 6 9]]


In [89]:
#Q84. Generate a square matrix `F` and compute its determinant
arr=nm.random.randint(1,10,(3,3))
print(arr)
print(np.linalg.det(arr))


[[7 4 8]
 [7 7 1]
 [3 1 7]]
40.000000000000014


In [90]:
#Q85. Create a square matrix `G` and find its inverse.
arr=nm.random.randint(1,10,(3,3))
print(np.linalg.inv(arr))

[[ 0.33333333  0.         -0.33333333]
 [ 0.33333333  3.         -2.33333333]
 [-0.33333333 -1.33333333  1.33333333]]
